jobs:
- job: macos_clang_8_debug
  displayName: 'include-what-you-use: macOS Clang 8 debug'

  pool:
    vmImage: macOS-10.13

  variables:
    # CXXTRACE_SOURCEDIRECTORY
    cxxtrace.SourceDirectory: $(System.DefaultWorkingDirectory)
    # CXXTRACE_BUILDDIRECTORY
    cxxtrace.BuildDirectory: $(System.DefaultWorkingDirectory)/build
    # CXXTRACE_IWYUDIRECTORY
    cxxtrace.IWYUDirectory: $(System.DefaultWorkingDirectory)/include-what-you-use
    # CXXTRACE_IWYUARCHIVENAME
    cxxtrace.IWYUArchiveName: include-what-you-use-0.12-clang-8-macos.tar.gz
    # CXXTRACE_IWYUNAME
    cxxtrace.IWYUName: include-what-you-use-0.12-clang-8-macos
    # CXXTRACE_IWYUPRETTYNAME
    cxxtrace.IWYUPrettyName: include-what-you-use 0.12 Clang 8.0.0
    # CXXTRACE_TOOLCHAINDIRECTORY
    cxxtrace.ToolchainDirectory: $(System.DefaultWorkingDirectory)/toolchain
    # CXXTRACE_TOOLCHAINNAME
    cxxtrace.ToolchainName: clang+llvm-8.0.0-x86_64-apple-darwin
    # CXXTRACE_TOOLCHAINARCHIVENAME
    cxxtrace.ToolchainArchiveName: clang+llvm-8.0.0-x86_64-apple-darwin.tar.xz
    cxxtrace.ToolchainPrettyName: Clang 8.0.0
    # CXXTRACE_TEMPDIRECTORY
    cxxtrace.TempDirectory: $(Agent.TempDirectory)/cxxtrace

  steps:
  - script: |
     set -eux
     mkdir -p -- \
       "${CXXTRACE_BUILDDIRECTORY}" \
       "${CXXTRACE_TOOLCHAINDIRECTORY}"
    displayName: Configure checkout

  - template: install-clang-toolchain-steps.template.yaml
  - template: install-include-what-you-use-steps.template.yaml

  - script: |
     set -eux
     cxxtrace_toolchain_usr="${CXXTRACE_TOOLCHAINDIRECTORY}/usr"
     PATH="${CXXTRACE_IWYUDIRECTORY}/bin:${cxxtrace_toolchain_usr}/bin:${PATH}"
     cflags="-D_LIBCPP_DISABLE_AVAILABILITY -Wall -Wextra -pedantic -Wno-c99-extensions"
     ldflags="-L${cxxtrace_toolchain_usr}/lib ${cxxtrace_toolchain_usr}/lib/libc++.a ${cxxtrace_toolchain_usr}/lib/libc++abi.a ${cxxtrace_toolchain_usr}/lib/libc++experimental.a ${cxxtrace_toolchain_usr}/lib/libc++fs.a"
     cmake \
       -G 'Unix Makefiles' \
       -DBUILD_TESTING=ON \
       -DCMAKE_BUILD_TYPE=Debug \
       -DCMAKE_C_COMPILER=clang \
       -DCMAKE_CXX_COMPILER=clang++ \
       -DCMAKE_C_FLAGS="${cflags}" \
       -DCMAKE_CXX_FLAGS="${cflags}" \
       -DCMAKE_EXE_LINKER_FLAGS="${ldflags}" \
       -DCMAKE_SHARED_LINKER_FLAGS="${ldflags}" \
       -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
       "${CXXTRACE_SOURCEDIRECTORY}"
    displayName: Configure cxxtrace
    workingDirectory: $(cxxtrace.BuildDirectory)
    timeoutInMinutes: 180

  - script: |
     set -eux
     PATH="${CXXTRACE_IWYUDIRECTORY}/bin:${cxxtrace_toolchain_usr}/bin:${PATH}"
     ./tools/format
     git add --update
     git commit --allow-empty --message 'Format sources'
    displayName: Format sources
    workingDirectory: $(cxxtrace.SourceDirectory)

  - script: |
     set -eux
     PATH="${CXXTRACE_IWYUDIRECTORY}/bin:${cxxtrace_toolchain_usr}/bin:${PATH}"
     cmake --build . -- include-what-you-use
     ./tools/format
    displayName: Run include-what-you-use
    workingDirectory: $(cxxtrace.BuildDirectory)

  - script: |
     set -eux
     if git diff --exit-code; then
       printf 'include-what-you-use introduced no differences\n' >&2
       exit 0
     else
       printf 'include-what-you-use introduced some differences\n' >&2
       exit 1
     fi
    displayName: Check include-what-you-use results
    workingDirectory: $(cxxtrace.SourceDirectory)
