jobs:
- job: macos_clang_8_debug
  displayName: 'include-what-you-use: macOS Clang 8 debug'

  pool:
    vmImage: macOS-10.13

  variables:
    # CXXTRACE_SOURCEDIRECTORY
    cxxtrace.SourceDirectory: $(System.DefaultWorkingDirectory)
    # CXXTRACE_BUILDDIRECTORY
    cxxtrace.BuildDirectory: $(System.DefaultWorkingDirectory)/build
    # CXXTRACE_IWYUDIRECTORY
    cxxtrace.IWYUDirectory: $(System.DefaultWorkingDirectory)/include-what-you-use
    # CXXTRACE_IWYUARCHIVENAME
    cxxtrace.IWYUArchiveName: include-what-you-use-0.12-clang-8-macos.tar.gz
    # CXXTRACE_IWYUNAME
    cxxtrace.IWYUName: include-what-you-use-0.12-clang-8-macos
    # CXXTRACE_IWYUPRETTYNAME
    cxxtrace.IWYUPrettyName: include-what-you-use 0.12 Clang 8.0.0
  # @@@ dedupe with build-and-test.yaml
    # CXXTRACE_TOOLCHAINDIRECTORY
    cxxtrace.ToolchainDirectory: $(System.DefaultWorkingDirectory)/toolchain
    # CXXTRACE_TOOLCHAINNAME
    cxxtrace.ToolchainName: clang+llvm-8.0.0-x86_64-apple-darwin
    # CXXTRACE_TOOLCHAINARCHIVENAME
    cxxtrace.ToolchainArchiveName: clang+llvm-8.0.0-x86_64-apple-darwin.tar.xz
    cxxtrace.ToolchainPrettyName: Clang 8.0.0
    # CXXTRACE_TEMPDIRECTORY
    cxxtrace.TempDirectory: $(Agent.TempDirectory)/cxxtrace

  steps:
  - script: |
     set -eux
     mkdir -p -- \
       "${CXXTRACE_BUILDDIRECTORY}" \
       "${CXXTRACE_TOOLCHAINDIRECTORY}"
    displayName: Configure checkout

  - task: DownloadPipelineArtifact@2
    displayName: Download $(cxxtrace.IWYUPrettyName)
    inputs:
      buildType: specific
      project: $(System.TeamProjectId)
      definition: 11 # build-include-what-you-use.yaml
      buildVersionToDownload: latest
      artifactName: $(cxxtrace.IWYUArchiveName)
      targetPath: $(cxxtrace.TempDirectory)/include-what-you-use.tar.gz
    timeoutInMinutes: 120

  - script: |
     set -eux
     mkdir -p -- "${CXXTRACE_IWYUDIRECTORY}"
     tar xf include-what-you-use.tar.gz -C "${CXXTRACE_IWYUDIRECTORY}" --strip-components 1
    displayName: Install $(cxxtrace.IWYUPrettyName)
    workingDirectory: $(cxxtrace.TempDirectory)
    timeoutInMinutes: 60

  - script: |
     set -eux
     ls -l $(cxxtrace.IWYUDirectory)/bin
     PATH="${CXXTRACE_IWYUDIRECTORY}/bin:${PATH}"
     include-what-you-use --version
     exit 42
    displayName: "@@@ debug"
    workingDirectory: $(cxxtrace.BuildDirectory)

  # @@@ dedupe with build-and-test.yaml
  - task: DownloadPipelineArtifact@2
    displayName: Download $(cxxtrace.ToolchainPrettyName)
    inputs:
      buildType: specific
      project: $(System.TeamProjectId)
      definition: 7 # cache-public-packages.yaml
      buildVersionToDownload: latest
      artifactName: $(cxxtrace.ToolchainArchiveName)
      targetPath: $(cxxtrace.ToolchainDirectory)
    timeoutInMinutes: 120

  # @@@ dedupe with build-and-test.yaml
  - script: |
     set -eux
     ls -laR
     tar xf "${CXXTRACE_TOOLCHAINARCHIVENAME}"
     ln -s -- "${CXXTRACE_TOOLCHAINNAME}" usr
    displayName: Install $(cxxtrace.ToolchainPrettyName)
    workingDirectory: $(cxxtrace.ToolchainDirectory)
    timeoutInMinutes: 60

  # @@@ dedupe with build-and-test.yaml?
  - script: |
     set -eux
     cxxtrace_toolchain_usr="${CXXTRACE_TOOLCHAINDIRECTORY}/usr"
     PATH="${CXXTRACE_IWYUDIRECTORY}/bin:${cxxtrace_toolchain_usr}/bin:${PATH}"
     cflags="-D_LIBCPP_DISABLE_AVAILABILITY -Wall -Wextra -pedantic -Wno-c99-extensions"
     ldflags="-L${cxxtrace_toolchain_usr}/lib ${cxxtrace_toolchain_usr}/lib/libc++.a ${cxxtrace_toolchain_usr}/lib/libc++abi.a ${cxxtrace_toolchain_usr}/lib/libc++experimental.a ${cxxtrace_toolchain_usr}/lib/libc++fs.a"
     cmake \
       -G 'Unix Makefiles' \
       -DBUILD_TESTING=ON \
       -DCMAKE_BUILD_TYPE=Debug \
       -DCMAKE_C_COMPILER=clang \
       -DCMAKE_CXX_COMPILER=clang++ \
       -DCMAKE_C_FLAGS="${cflags}" \
       -DCMAKE_CXX_FLAGS="${cflags}" \
       -DCMAKE_EXE_LINKER_FLAGS="${ldflags}" \
       -DCMAKE_SHARED_LINKER_FLAGS="${ldflags}" \
       -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
       "${CXXTRACE_SOURCEDIRECTORY}"
    displayName: Configure cxxtrace
    workingDirectory: $(cxxtrace.BuildDirectory)
    timeoutInMinutes: 180

  - script: |
     set -eux
     PATH="${CXXTRACE_IWYUDIRECTORY}/bin:${PATH}"
     cmake --build . -- include-what-you-use
    displayName: Run include-what-you-use
    workingDirectory: $(cxxtrace.BuildDirectory)

  - script: |
     set -eux
     git diff
    displayName: Check include-what-you-use results
    workingDirectory: $(cxxtrace.SourceDirectory)

# @@@ Linux plz
